name: my_btc_balance
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  get: 4.6.6
  hexcolor: ^3.0.1
 
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/lock.png
    - assets/trancar.png
    - assets/bitcoin-wallet.png
    - assets/safe-box.png

